title: "Krupa's Portfolio"
description: Personal portfolio website
baseurl: "/krupa-portfolio"  # GitHub Pages default - overridden in _config_dev.yml for local
url: "https://krupabpatel.github.io"  # GitHub Pages default - overridden in _config_dev.yml for local

# GitHub Pages settings
repository: "krupabpatel/krupa-portfolio"

# Build settings
markdown: kramdown
# theme: minima
# plugins:
#   - jekyll-feed
#   - jekyll-sitemap

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata