title: Krupa's Portfolio
description: Personal portfolio website
baseurl: ""
url: "https://USERNAME.github.io"

# Build settings
markdown: kramdown
# theme: minima
# plugins:
#   - jekyll-feed
#   - jekyll-sitemap

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata