title: "Krupa Patel"
description: "Krupa Patel - Product Manager"
baseurl: ""  # Custom domain uses root path
url: "https://kroops.me"

# GitHub Pages settings
repository: "krupabpatel/krupa-portfolio"

# Build settings
markdown: kramdown
# theme: minima
# plugins:
#   - jekyll-feed
#   - jekyll-sitemap

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:slug/
  hero:
    output: false
  sections:
    output: false
  education:
    output: false
  experience:
    output: false
  skills:
    output: false

# Defaults
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata