# Decap CMS Configuration for GitHub Pages
backend:
  name: github
  repo: krupabpatel/krupa-portfolio
  branch: main
  base_url: https://cms-auth-proxy-kroops.anshuldesai.workers.dev
  auth_endpoint: auth

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "projects"
    label: "Projects"
    folder: "_projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "project" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "URL Slug", name: "slug", widget: "string", hint: "URL-friendly name (e.g., 'my-project' becomes /projects/my-project/)", pattern: ['^[a-z0-9-]+$', "Only lowercase letters, numbers, and hyphens allowed"] }
      - { label: "Summary", name: "summary", widget: "text", hint: "Short description for project cards on homepage" }
      - { label: "Role", name: "role", widget: "string" }
      - { label: "Tools Used", name: "tools", widget: "list", allow_add: true, field: { label: "Tool", name: "tool", widget: "string" } }
      - { label: "Content", name: "body", widget: "markdown", hint: "Main project description" }
      - label: "Media"
        name: "media"
        widget: "list"
        required: false
        hint: "Images, videos, and Figma embeds for the carousel"
        types:
          - label: "Image"
            name: "image"
            fields:
              - { label: "Type", name: "type", widget: "hidden", default: "image" }
              - { label: "Image URL/Upload", name: "src", widget: "string", hint: "Upload a file or enter external image URL" }
              - { label: "Alt Text", name: "alt", widget: "string" }
              - { label: "Caption", name: "caption", widget: "text", required: false }
          - label: "Video"
            name: "video"
            fields:
              - { label: "Type", name: "type", widget: "hidden", default: "video" }
              - { label: "Video URL/Upload", name: "src", widget: "string", hint: "Upload a file or enter external video URL" }
              - { label: "Alt Text", name: "alt", widget: "string" }
              - { label: "Caption", name: "caption", widget: "text", required: false }
          - label: "Figma Embed"
            name: "embed"
            fields:
              - { label: "Type", name: "type", widget: "hidden", default: "embed" }
              - { label: "Figma Embed Code", name: "embed", widget: "text" }
              - { label: "Caption", name: "caption", widget: "text", required: false }
      - label: "Links"
        name: "links"
        widget: "list"
        required: false
        hint: "Downloadable files and resources (upload files or use external URLs)"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "URL/File", name: "url", widget: "string", hint: "Upload a file or enter external URL" }
          - { label: "External Link", name: "external", widget: "boolean", default: false, hint: "Check if this is an external URL" }