# Decap CMS Configuration for GitHub Pages
backend:
  name: github
  repo: krupabpatel/krupa-portfolio
  branch: main
  base_url: https://cms-auth-proxy-kroops.anshuldesai.workers.dev
  auth_endpoint: auth

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "hero"
    label: "Hero Section"
    files:
      - label: "Hero Content"
        name: "hero"
        file: "_hero/hero.md"
        fields:
          - { label: "Hero Title", name: "title", widget: "string" }
          - { label: "Hero Subtitle", name: "subtitle", widget: "text" }
          - { label: "Profile Image", name: "image", widget: "image", media_folder: "/assets/images", public_folder: "/assets/images" }
          - { label: "Image Alt Text", name: "image_alt", widget: "string" }
          - { label: "Connect URL (LinkedIn)", name: "connect_url", widget: "string" }
          - { label: "Contact Email", name: "contact_email", widget: "string" }

  - name: "projects"
    label: "Projects"
    folder: "_projects"
    create: true
    slug: "{{fields.slug}}"
    identifier_field: title
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "project" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "URL Slug", name: "slug", widget: "string", hint: "URL-friendly name (e.g., 'my-project' becomes /projects/my-project/)", pattern: ['^[a-z0-9-]+$', "Only lowercase letters, numbers, and hyphens allowed"] }
      - { label: "Display Order", name: "order", widget: "number", default: 1, hint: "Lower numbers appear first on homepage" }
      - { label: "Summary", name: "summary", widget: "text", hint: "Short description for project cards on homepage" }
      - { label: "Role", name: "role", widget: "string" }
      - { label: "Tools Used", name: "tools", widget: "list", allow_add: true, field: { label: "Tool", name: "tool", widget: "string" } }
      - { label: "Content", name: "body", widget: "markdown", hint: "Main project description" }
      - label: "Media"
        name: "media"
        widget: "list"
        required: false
        hint: "Images, videos, and Figma embeds for the carousel"
        types:
          - label: "Image"
            name: "image"
            fields:
              - { label: "Type", name: "type", widget: "hidden", default: "image" }
              - { label: "Image", name: "src", widget: "image", media_folder: "/assets/images", public_folder: "/assets/images" }
              - { label: "Alt Text", name: "alt", widget: "string" }
              - { label: "Caption", name: "caption", widget: "text", required: false }
          - label: "Video"
            name: "video"
            fields:
              - { label: "Type", name: "type", widget: "hidden", default: "video" }
              - { label: "Video File", name: "src", widget: "file", media_folder: "/assets/videos", public_folder: "/assets/videos" }
              - { label: "Alt Text", name: "alt", widget: "string" }
              - { label: "Caption", name: "caption", widget: "text", required: false }
          - label: "Figma Embed"
            name: "embed"
            fields:
              - { label: "Type", name: "type", widget: "hidden", default: "embed" }
              - { label: "Figma Embed Code", name: "embed", widget: "text" }
              - { label: "Caption", name: "caption", widget: "text", required: false }
      - label: "Links"
        name: "links"
        widget: "list"
        required: false
        hint: "Downloadable files and resources (upload files or use external URLs)"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "File", name: "url", widget: "file", media_folder: "/assets/docs", public_folder: "/assets/docs" }
          - { label: "External Link", name: "external", widget: "boolean", default: false, hint: "Check if this is an external URL" }

  - name: "sections"
    label: "Homepage Sections"
    files:
      - label: "Section Subtitles"
        name: "sections"
        file: "_sections/sections.md"
        fields:
          - { label: "Projects Subtitle", name: "projects_subtitle", widget: "text", hint: "Subtitle text under the Projects section" }
          - { label: "Resume Subtitle", name: "resume_subtitle", widget: "text", hint: "Subtitle text under the Resume section" }
          - { label: "Footer Subtitle", name: "footer_subtitle", widget: "text", hint: "Subtitle text in the footer contact section" }

  - name: "education"
    label: "Education"
    folder: "_education"
    create: true
    slug: "{{degree}}"
    identifier_field: degree
    fields:
      - { label: "Display Order", name: "order", widget: "number", default: 1, hint: "Lower numbers appear first" }
      - { label: "Degree", name: "degree", widget: "string", hint: "e.g., Master of Business Administration - MBA" }
      - { label: "Institution", name: "institution", widget: "string", hint: "University or school name" }
      - { label: "Location", name: "location", widget: "string", hint: "City, State" }
      - { label: "Date", name: "graduation_date", widget: "string", hint: "e.g., May 2025" }
      - label: "Details"
        name: "details"
        widget: "list"
        required: false
        hint: "Add category/description pairs (e.g., Concentrations, Honors, Leadership)"
        fields:
          - { label: "Category", name: "category", widget: "string", hint: "e.g., Concentrations, Honors, Leadership" }
          - { label: "Body", name: "body", widget: "text", hint: "The description text for this category" }

  - name: "experience"
    label: "Experience" 
    folder: "_experience"
    create: true
    slug: "{{title}}"
    summary: "{{company}} - {{title}}"
    fields:
      - { label: "Display Order", name: "order", widget: "number", default: 1, hint: "Lower numbers appear first" }
      - { label: "Job Title", name: "title", widget: "string", hint: "e.g., Product and Operations MBA Intern" }
      - { label: "Company", name: "company", widget: "string", hint: "Company name and department" }
      - { label: "Location", name: "location", widget: "string", hint: "City, State" }
      - { label: "Date Range", name: "date_range", widget: "string", hint: "e.g., June 2024 – August 2024" }
      - label: "Responsibilities"
        name: "responsibilities"
        widget: "list"
        required: false
        hint: "Add category/description pairs for job responsibilities"
        fields:
          - { label: "Category", name: "category", widget: "string", hint: "e.g., Product Roadmap Definition" }
          - { label: "Description", name: "description", widget: "text", hint: "Detailed description of the responsibility" }

  - name: "skills"
    label: "Skills & Certifications"
    folder: "_skills"
    create: true
    slug: "{{category_name}}"
    identifier_field: category_name
    fields:
      - { label: "Display Order", name: "order", widget: "number", default: 1, hint: "Lower numbers appear first" }
      - { label: "Category Name", name: "category_name", widget: "string", hint: "e.g., Product Management & Strategy" }
      - { label: "Color Theme", name: "color", widget: "select", options: ["tan", "lavender"], default: "tan", hint: "Bubble color for skill tags" }
      - label: "Skills"
        name: "skills"
        widget: "list"
        required: false
        hint: "Add individual skills or certifications"
        fields:
          - { label: "Skill/Certification", name: "name", widget: "string", hint: "e.g., Product Strategy & Development" }