name: Organize PDFs

on:
  push:
    branches: [ main ]

run-name: "Organize PDFs Action: ${{ github.event.head_commit.message }}"

permissions:
  contents: write

jobs:
  organize-pdfs:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[via-sveltia]')
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
        persist-credentials: true

    - name: Organize PDFs
      run: |
        echo "Running PDF organization..."
        
        # Initialize variables
        CLEANUP_MADE=false
        
        # Function to clean up orphaned PDFs
        cleanup_orphaned_pdfs() {
          echo "Checking for orphaned PDFs in assets/docs..."
          if ls assets/docs/*.pdf 1> /dev/null 2>&1; then
            for pdf in assets/docs/*.pdf; do
              filename=$(basename "$pdf")
              # Check if this PDF is referenced in any markdown files
              if ! grep -r "/assets/docs/$filename" _projects/ . --include="*.md" > /dev/null 2>&1; then
                echo "Removing orphaned PDF: $filename"
                rm "$pdf"
                CLEANUP_MADE=true
              fi
            done
          fi
        }
        
        # Clean up orphaned PDFs first
        cleanup_orphaned_pdfs
        
        echo "Checking for PDFs in assets/images..."
        
        # Check if any PDFs exist in assets/images
        if ls assets/images/*.pdf 1> /dev/null 2>&1; then
          echo "Found PDF(s) in assets/images, moving to assets/docs..."
          
          # Create docs directory if it doesn't exist
          mkdir -p assets/docs
          
          # Track if any files were moved
          MOVED_FILES=false
          
          # Move each PDF and update references
          for pdf in assets/images/*.pdf; do
            if [[ -f "$pdf" ]]; then
              # Get the filename
              filename=$(basename "$pdf")
              
              # Move the file
              mv "$pdf" "assets/docs/$filename"
              echo "Moved: $pdf → assets/docs/$filename"
              
              # Update references in markdown files
              find _projects -name "*.md" -exec sed -i "s|/assets/images/$filename|/assets/docs/$filename|g" {} \;
              find . -maxdepth 1 -name "*.md" -exec sed -i "s|/assets/images/$filename|/assets/docs/$filename|g" {} \;
              
              echo "Updated references from $filename"
              MOVED_FILES=true
            fi
          done
          
          # Track if files were moved
          if [[ "$MOVED_FILES" == true ]]; then
            echo "Files were moved from assets/images"
          fi
        else
          echo "No PDFs found in assets/images"
        fi
        
        # Commit and push changes if files were moved or cleanup was made
        if [[ "$MOVED_FILES" == true ]] || [[ "$CLEANUP_MADE" == true ]]; then
          git config --local user.email "krupa.b.patel@outlook.com"
          git config --local user.name "Krupa Patel"
          git add .
          git commit --amend --no-edit
          git push --force-with-lease
          echo "Organized PDFs and updated original commit"
        else
          echo "No PDF organization changes were needed"
        fi